# Header
menu:
  Home: /
  Archives: /archives

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- archive
- tag
- tagcloud
- recent_posts
- links

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

# blogroll
links:
- name: Yuuki_Dach's GitHub
  link: https://github.com/yuukidach
- name: Yuuki_Dach's CSDN
  link: http://blog.csdn.net/the_madao
- name: Dandeliar's Blog
  link: https://bibi-fish.github.io

